// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migfggdvdfdfddddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migfggdvdfdfddddd));
        
        string IMigrationMetadata.Id
        {
            get { return "202411121211466_mig-fggdvdfdfddddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
